name:                pikkuc
version:             0.1.0.0
github:              "peksin/pikkuc"
license:             MIT
author:              "Pekka Sinkkonen"
maintainer:          "peksin@protonmail.com"
copyright:           "2021 Pekka Sinkkonen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/peksin/pikkuc#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- array
- containers
- text
- string-conversions
- directory
- process
- unix
- filepath
- bytestring
- prettyprinter
- llvm-hs-pure
- llvm-hs-pretty
- megaparsec
- parser-combinators
- optparse-applicative
- hspec
- hspec-megaparsec

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings
    - LambdaCase

executables:
  pikkuc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pikkuc

tests:
  pikkuc-unit-tests:
    main:                Spec.hs
    source-dirs:         test/unit
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pikkuc
    - hspec-discover
    default-extensions:
      - OverloadedStrings
